### ISSUE TITLE
feature request: mac-os support

### ISSUE THREAD

**Issue by ekiwi** [YosysHQ/setup-oss-cad-suite#1]
It would be great if this action also worked on `mac-os`. Since most users of Chisel are using mac to do their development I try to have at least some MacOS tests in the `chiseltest` CI: https://github.com/ucb-bar/chisel-testers2/pull/441

**Comment by mmicko** [comment]
Understand. Will take care of this tomorrow.

**Comment by mmicko** [comment]
setup is now available for macOS machines as well
