### ISSUE TITLE
Unable to get download URL for oss-cad-suite package

### ISSUE THREAD

**Issue by olofk** [YosysHQ/setup-oss-cad-suite#8]
I'm using this for a GH CI action (https://github.com/olofk/serv/actions/workflows/formal.yml) and today it started failing with:
```
Run YosysHQ/setup-oss-cad-suite@v3
  with:
    github-token: ***
    python-override: false
Setting up oss-cad-suite
Getting download URL for oss-cad-suite-linux-x64
Error: Unable to get download URL for oss-cad-suite package
```

Not sure how to debug this further on my side.

**Comment by mmicko** [comment]
Hi @olofk, it is very rare but happens that gihub action timesout before last step or during upload of release. This night was such occasion. I have rerun that job and now it fine. Please just re-run that failed job. One thing that could be done in setup action would be first to check existance of tar.gz and if not uploaded for some reason to try one day older release before failing

**Comment by olofk** [comment]
Yes! Now it runs. Thanks for looking into this. And good to know it might occasionally fail if I run across this again. Closing.
